// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	HashSet
	Request
	AddHash
	Search
	Response
	SearchResults
	ErrorInfo
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestType int32

const (
	RequestType_ADD_HASH RequestType = 0
	RequestType_SEARCH   RequestType = 2
)

var RequestType_name = map[int32]string{
	0: "ADD_HASH",
	2: "SEARCH",
}
var RequestType_value = map[string]int32{
	"ADD_HASH": 0,
	"SEARCH":   2,
}

func (x RequestType) String() string {
	return proto.EnumName(RequestType_name, int32(x))
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ResponseType int32

const (
	ResponseType_SUCCESS ResponseType = 0
	ResponseType_ERROR   ResponseType = 1
)

var ResponseType_name = map[int32]string{
	0: "SUCCESS",
	1: "ERROR",
}
var ResponseType_value = map[string]int32{
	"SUCCESS": 0,
	"ERROR":   1,
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}
func (ResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type HashSet struct {
	Hashes []uint64 `protobuf:"varint,1,rep,packed,name=hashes" json:"hashes,omitempty"`
}

func (m *HashSet) Reset()                    { *m = HashSet{} }
func (m *HashSet) String() string            { return proto.CompactTextString(m) }
func (*HashSet) ProtoMessage()               {}
func (*HashSet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HashSet) GetHashes() []uint64 {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type Request struct {
	Type    RequestType `protobuf:"varint,1,opt,name=type,enum=model.RequestType" json:"type,omitempty"`
	Payload []byte      `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetType() RequestType {
	if m != nil {
		return m.Type
	}
	return RequestType_ADD_HASH
}

func (m *Request) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type AddHash struct {
	HashSet *HashSet `protobuf:"bytes,1,opt,name=hashSet" json:"hashSet,omitempty"`
}

func (m *AddHash) Reset()                    { *m = AddHash{} }
func (m *AddHash) String() string            { return proto.CompactTextString(m) }
func (*AddHash) ProtoMessage()               {}
func (*AddHash) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddHash) GetHashSet() *HashSet {
	if m != nil {
		return m.HashSet
	}
	return nil
}

type Search struct {
	Hash     uint64 `protobuf:"varint,1,opt,name=hash" json:"hash,omitempty"`
	Distance uint32 `protobuf:"varint,2,opt,name=distance" json:"distance,omitempty"`
}

func (m *Search) Reset()                    { *m = Search{} }
func (m *Search) String() string            { return proto.CompactTextString(m) }
func (*Search) ProtoMessage()               {}
func (*Search) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Search) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

func (m *Search) GetDistance() uint32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type Response struct {
	Type    ResponseType `protobuf:"varint,1,opt,name=type,enum=model.ResponseType" json:"type,omitempty"`
	Payload []byte       `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Response) GetType() ResponseType {
	if m != nil {
		return m.Type
	}
	return ResponseType_SUCCESS
}

func (m *Response) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type SearchResults struct {
	Hashes []uint64 `protobuf:"varint,1,rep,packed,name=hashes" json:"hashes,omitempty"`
}

func (m *SearchResults) Reset()                    { *m = SearchResults{} }
func (m *SearchResults) String() string            { return proto.CompactTextString(m) }
func (*SearchResults) ProtoMessage()               {}
func (*SearchResults) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SearchResults) GetHashes() []uint64 {
	if m != nil {
		return m.Hashes
	}
	return nil
}

type ErrorInfo struct {
	Info string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *ErrorInfo) Reset()                    { *m = ErrorInfo{} }
func (m *ErrorInfo) String() string            { return proto.CompactTextString(m) }
func (*ErrorInfo) ProtoMessage()               {}
func (*ErrorInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ErrorInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*HashSet)(nil), "model.HashSet")
	proto.RegisterType((*Request)(nil), "model.Request")
	proto.RegisterType((*AddHash)(nil), "model.AddHash")
	proto.RegisterType((*Search)(nil), "model.Search")
	proto.RegisterType((*Response)(nil), "model.Response")
	proto.RegisterType((*SearchResults)(nil), "model.SearchResults")
	proto.RegisterType((*ErrorInfo)(nil), "model.ErrorInfo")
	proto.RegisterEnum("model.RequestType", RequestType_name, RequestType_value)
	proto.RegisterEnum("model.ResponseType", ResponseType_name, ResponseType_value)
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcf, 0x6b, 0xfa, 0x40,
	0x10, 0xc5, 0x8d, 0xdf, 0x98, 0x98, 0xf1, 0x07, 0x61, 0xbe, 0x50, 0x42, 0x2f, 0xb5, 0x39, 0x68,
	0xf0, 0xe0, 0x41, 0x2f, 0xbd, 0x06, 0x0d, 0xa4, 0x94, 0x52, 0x98, 0x6d, 0xcf, 0x65, 0x6b, 0x46,
	0x22, 0xd8, 0x6c, 0x9a, 0x8d, 0x07, 0xff, 0xfb, 0xe2, 0x1a, 0xc5, 0x1e, 0x0a, 0xbd, 0xcd, 0xdb,
	0xc7, 0xbe, 0xf7, 0x61, 0x06, 0x3c, 0x59, 0x6e, 0x67, 0x65, 0xa5, 0x6a, 0x85, 0x9d, 0x4f, 0x95,
	0xf1, 0x2e, 0xbc, 0x07, 0x37, 0x95, 0x3a, 0x17, 0x5c, 0xe3, 0x0d, 0x38, 0xb9, 0xd4, 0x39, 0xeb,
	0xc0, 0x1a, 0xfd, 0x8b, 0x6c, 0x6a, 0x54, 0xf8, 0x04, 0x2e, 0xf1, 0xd7, 0x9e, 0x75, 0x8d, 0x63,
	0xb0, 0xeb, 0x43, 0xc9, 0x81, 0x35, 0xb2, 0xa2, 0xe1, 0x1c, 0x67, 0x26, 0x63, 0xd6, 0xb8, 0xaf,
	0x87, 0x92, 0xc9, 0xf8, 0x18, 0x80, 0x5b, 0xca, 0xc3, 0x4e, 0xc9, 0x2c, 0x68, 0x8f, 0xac, 0xa8,
	0x4f, 0x67, 0x19, 0x2e, 0xc0, 0x8d, 0xb3, 0xec, 0x58, 0x89, 0x11, 0xb8, 0xf9, 0xa9, 0xda, 0xe4,
	0xf5, 0xe6, 0xc3, 0x26, 0xaf, 0x01, 0xa2, 0xb3, 0x1d, 0x3e, 0x80, 0x23, 0x58, 0x56, 0xeb, 0x1c,
	0x11, 0xec, 0xe3, 0xa3, 0xf9, 0x60, 0x93, 0x99, 0xf1, 0x16, 0xba, 0xd9, 0x56, 0xd7, 0xb2, 0x58,
	0xb3, 0x69, 0x1b, 0xd0, 0x45, 0x87, 0xcf, 0xd0, 0x25, 0xd6, 0xa5, 0x2a, 0x34, 0xe3, 0xe4, 0x07,
	0xfc, 0xff, 0x0b, 0xfc, 0xc9, 0xfe, 0x13, 0xfd, 0x04, 0x06, 0x27, 0x10, 0x62, 0xbd, 0xdf, 0xd5,
	0xfa, 0xd7, 0x9d, 0xdd, 0x81, 0x97, 0x54, 0x95, 0xaa, 0x1e, 0x8b, 0x8d, 0x3a, 0x42, 0x6f, 0x8b,
	0x8d, 0x32, 0xc5, 0x1e, 0x99, 0x79, 0x3a, 0x81, 0xde, 0xd5, 0xda, 0xb0, 0x0f, 0xdd, 0x78, 0xb5,
	0x7a, 0x4f, 0x63, 0x91, 0xfa, 0x2d, 0x04, 0x70, 0x44, 0x12, 0xd3, 0x32, 0xf5, 0xdb, 0xd3, 0x31,
	0xf4, 0xaf, 0x11, 0xb1, 0x07, 0xae, 0x78, 0x5b, 0x2e, 0x13, 0x21, 0xfc, 0x16, 0x7a, 0xd0, 0x49,
	0x88, 0x5e, 0xc8, 0xb7, 0x3e, 0x1c, 0x73, 0xd6, 0xc5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e,
	0x27, 0x88, 0x82, 0xe3, 0x01, 0x00, 0x00,
}
